[2024-06-26T14:40:05.799+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T14:40:05.900+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launches_dag.download_lauches manual__2024-06-26T14:39:58.622882+00:00 [queued]>
[2024-06-26T14:40:05.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launches_dag.download_lauches manual__2024-06-26T14:39:58.622882+00:00 [queued]>
[2024-06-26T14:40:05.925+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-26T14:40:05.960+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): download_lauches> on 2024-06-26 14:39:58.622882+00:00
[2024-06-26T14:40:05.988+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=103) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T14:40:05.997+0000] {standard_task_runner.py:63} INFO - Started process 104 to run task
[2024-06-26T14:40:05.996+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'rocket_launches_dag', 'download_lauches', 'manual__2024-06-26T14:39:58.622882+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launches_dag.py', '--cfg-path', '/tmp/tmpb20d4jpm']
[2024-06-26T14:40:05.998+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask download_lauches
[2024-06-26T14:40:06.127+0000] {task_command.py:426} INFO - Running <TaskInstance: rocket_launches_dag.download_lauches manual__2024-06-26T14:39:58.622882+00:00 [running]> on host 47ee3db5e190
[2024-06-26T14:40:06.382+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rocket_launches_dag' AIRFLOW_CTX_DAG_ID='rocket_launches_dag' AIRFLOW_CTX_TASK_ID='download_lauches' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T14:39:58.622882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T14:39:58.622882+00:00'
[2024-06-26T14:40:06.388+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T14:40:06.529+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-26T14:40:06.534+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "curl -o /tmp/launches.json -L 'https://ll.thespacedevs.com/2.0.0/launch/upcoming'"]
[2024-06-26T14:40:06.567+0000] {subprocess.py:86} INFO - Output:
[2024-06-26T14:40:06.620+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-06-26T14:40:06.621+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-06-26T14:40:14.661+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0curl: (6) Could not resolve host: ll.thespacedevs.com
[2024-06-26T14:40:14.666+0000] {subprocess.py:97} INFO - Command exited with return code 6
[2024-06-26T14:40:14.676+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T14:40:14.714+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 6.
[2024-06-26T14:40:14.743+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=rocket_launches_dag, task_id=download_lauches, run_id=manual__2024-06-26T14:39:58.622882+00:00, execution_date=20240626T143958, start_date=20240626T144005, end_date=20240626T144014
[2024-06-26T14:40:14.775+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task download_lauches (Bash command failed. The command returned a non-zero exit code 6.; 104)
[2024-06-26T14:40:14.804+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-26T14:40:14.852+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T14:40:14.853+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
