[2024-06-27T15:05:39.128+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T15:05:39.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launches_dag.get_pictures manual__2024-06-26T15:26:50.780640+00:00 [queued]>
[2024-06-27T15:05:39.382+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launches_dag.get_pictures manual__2024-06-26T15:26:50.780640+00:00 [queued]>
[2024-06-27T15:05:39.384+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-27T15:05:39.434+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_pictures> on 2024-06-26 15:26:50.780640+00:00
[2024-06-27T15:05:39.511+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'rocket_launches_dag', 'get_pictures', 'manual__2024-06-26T15:26:50.780640+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launches_dag.py', '--cfg-path', '/tmp/tmpq673ftt3']
[2024-06-27T15:05:39.489+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=361) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-27T15:05:39.526+0000] {standard_task_runner.py:91} INFO - Job 40: Subtask get_pictures
[2024-06-27T15:05:39.527+0000] {standard_task_runner.py:63} INFO - Started process 363 to run task
[2024-06-27T15:05:39.959+0000] {task_command.py:426} INFO - Running <TaskInstance: rocket_launches_dag.get_pictures manual__2024-06-26T15:26:50.780640+00:00 [running]> on host 69160e04a996
[2024-06-27T15:05:40.173+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rocket_launches_dag' AIRFLOW_CTX_DAG_ID='rocket_launches_dag' AIRFLOW_CTX_TASK_ID='get_pictures' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T15:26:50.780640+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-26T15:26:50.780640+00:00'
[2024-06-27T15:05:40.175+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T15:05:40.313+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T15:05:40.317+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rocket_launches_dag.py", line 18, in _get_pictures
    with open("/tmp/launches.json") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/launches.json'
[2024-06-27T15:05:40.360+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=rocket_launches_dag, task_id=get_pictures, run_id=manual__2024-06-26T15:26:50.780640+00:00, execution_date=20240626T152650, start_date=20240627T150539, end_date=20240627T150540
[2024-06-27T15:05:40.383+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 40 for task get_pictures ([Errno 2] No such file or directory: '/tmp/launches.json'; 363)
[2024-06-27T15:05:40.442+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T15:05:40.476+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T15:05:40.477+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
