[2024-06-29T08:54:43.632+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T08:54:43.658+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rocket_launches_dag.get_pictures manual__2024-06-27T15:18:05.536862+00:00 [queued]>
[2024-06-29T08:54:43.671+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rocket_launches_dag.get_pictures manual__2024-06-27T15:18:05.536862+00:00 [queued]>
[2024-06-29T08:54:43.673+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-06-29T08:54:43.697+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_pictures> on 2024-06-27 15:18:05.536862+00:00
[2024-06-29T08:54:43.706+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-29T08:54:43.708+0000] {standard_task_runner.py:63} INFO - Started process 204 to run task
[2024-06-29T08:54:43.708+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'rocket_launches_dag', 'get_pictures', 'manual__2024-06-27T15:18:05.536862+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launches_dag.py', '--cfg-path', '/tmp/tmp17nksrih']
[2024-06-29T08:54:43.710+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask get_pictures
[2024-06-29T08:54:43.759+0000] {task_command.py:426} INFO - Running <TaskInstance: rocket_launches_dag.get_pictures manual__2024-06-27T15:18:05.536862+00:00 [running]> on host 1bf8b89f489e
[2024-06-29T08:54:43.858+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rocket_launches_dag' AIRFLOW_CTX_DAG_ID='rocket_launches_dag' AIRFLOW_CTX_TASK_ID='get_pictures' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T15:18:05.536862+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T15:18:05.536862+00:00'
[2024-06-29T08:54:43.860+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T08:54:43.874+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T08:54:43.875+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/rocket_launches_dag.py", line 18, in _get_pictures
    with open("/tmp/launches.json") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/launches.json'
[2024-06-29T08:54:43.891+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=rocket_launches_dag, task_id=get_pictures, run_id=manual__2024-06-27T15:18:05.536862+00:00, execution_date=20240627T151805, start_date=20240629T085443, end_date=20240629T085443
[2024-06-29T08:54:43.910+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 66 for task get_pictures ([Errno 2] No such file or directory: '/tmp/launches.json'; 204)
[2024-06-29T08:54:43.923+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-29T08:54:43.949+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T08:54:43.951+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
