[2024-06-24T16:05:08.336+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: first_dag.task1 scheduled__2021-08-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
